### PR TITLE
Mostly editorial changes

### PR DESCRIPTION
**Pull request by eliaskosunen**
Tons of typo fixes
Added some notes with prefix EK: (my initials)

Code style changed to be similar to the standard:
```cpp
template<class T, class... Ts>
void func(const T& a, Ts&&... b) {
  // foo
}
```

### CODE REVIEW

**Comment by eliaskosunen** [comment]
The diff is humongous, but there are no substantial changes; just typo fixes and whitespace changes, alongside some comments and notes

**Comment by JeffGarland** [comment]
Ok.  I've looked thru the first 1/2 and looks good.  Will get back to it in a bit....

**Comment by eliaskosunen** [comment]
I'll extract the notes/comments to a separate issue, they're just there so I wouldn't forget them

**Comment by JeffGarland** [comment]
that would be good - probably time to clean up the todos and notes

**Comment by eliaskosunen** [comment]
PR rebased against current master

Once this gets merged, I'll list the notes and comments to an issue

**Comment by JeffGarland** [comment]
Thanks for rebasing this!

**Pull request merged**
