### PR TITLE
Cologne feedback

### PR DESCRIPTION
**Pull request by eliaskosunen**
Only some of it, though; see commit messages

### CODE REVIEW

**Comment by eliaskosunen** [comment]
Might make sg1 a little more bearable by not having async in there

**Comment by JeffGarland** [comment]
I’m not going to pull it- SG1 needs to know about this and incorporate into their thinking.

**Comment by eliaskosunen** [comment]
The second commit mainly deals with making `pipe` byte-based. Although it's really up to you should you want to deal with compiling draft revisions or not.

**Comment by JeffGarland** [comment]
Yeah I wasn’t planning on doing any revisions until after the meeting.  As much as I agree with making the pipe byte-based on principle we will need to understand what impacts it has on the implementation ultimately.  So a plausible outcome will be that the proposal remains unchanged….

**Comment by eliaskosunen** [comment]
As SG1 ended up liking the async stuff, I reverted the commit

**Comment by eliaskosunen** [comment]
Something of note: the generated PDF is currently not compliant with N3370 "Call for Library Proposals": https://wg21.link/N3370, as it's missing a reply-to email address and an audience.

**Comment by eliaskosunen** [comment]
I would like to make note, that CppCon is in less than two weeks, and that I think the paper at this point is not in shape for the planned mock LEWG review.

**Comment by JeffGarland** [comment]
Yes and after the initial discussion of that idea we weren’t really in the running anyway.

Many apologies on my end that this has dropped off the table, but there’s a bunch of committee things (this will become clear with some future announcements) and some not good personal things that have kept me from working on this.  Elias I will get to those pull requests quite soon — and hopefully we can start shaping the update for Belfast. 

Jeff

**Comment by eliaskosunen** [comment]
> Yes and after the initial discussion of that idea we weren’t really in the running anyway.

And now it seems like the review session wouldn't be happening at all, so not really our problem anymore.

> but there’s a bunch of committee things (this will become clear with some future announcements)

I presume by this you mean the recent subgroup chair shuffle, which I'd say is pretty much public knowledge already (congrats btw), given that the information has been updated on the isocpp website: https://isocpp.org/std/the-committee#Subgroups. If you're referring to something else, then feel free to ignore what I just said.

> some not good personal things that have kept me from working on this

Sorry to hear that. Given that the CppCon review thingy should indeed not be happening, this is fortunately not as pressing anymore.

**Comment by JeffGarland** [comment]
> I presume by this you mean the recent subgroup chair shuffle, which I'd say is pretty much public knowledge already (congrats btw),

Yes - I now have 'an unknown set' of 'official duties' helping the LWG chair to keep me busier.

> Sorry to hear that.

Thanks.  And now I've made it urgent anyway to get this ready for Belfast mailing deadline :/  I've pulled your changes as the starting point and will be doing my best over the next ~36 hours to update based on feedback.  I'm sure some issues won't be addressed by the deadline -- but we can post an update pre-Belfast with some tweaks if need be.

**Pull request merged**
