### PR TITLE
Revision 2

### PR DESCRIPTION
**Pull request by klemens-morgenstern**
Revision 2  proposal - removed pipes and implemented extensible IO.

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
@JeffGarland Waht do you think about removing pipes? I know I was the one resisting that in the past, but it seems to me there is no way to get pipes with C++23, but maybe a process lite could do it.

**Comment by klemens-morgenstern** [comment]
Everything is implemented in a sloppy, untested and probably buggy way, which isn't compiling on MSVC anymore. Should be a proper start for reference: https://github.com/klemens-morgenstern/process/commit/74dcc3d2f5dceb7c6234bc371b7524518b471e3c

**Comment by klemens-morgenstern** [comment]
Also we must discuss #63 before merging.

**Comment by JeffGarland** [comment]
> @JeffGarland What do you think about removing pipes? I know I was the one resisting that in the past, but it seems to me there is no way to get pipes with C++23, but maybe a process lite could do it.

I see 3 ways we could go.  

1. Leave them and see what happens -- LEWG could just ask us to remove them -- it's been pretty close already on that -- we could offer the option and see what they say.
2. Put them in a different paper -- the problem there is if we specify using them then we'd need both anyway
3. drop them and simplify

At the moment if we can drop them and get basic functionality I think that would be the best way.  It would obviously be much simpler and we might have a shot at c++20.  With networking/executors and all that stuff as a top priority -- and the likelihood that there may only be 2 face to face meetings before 23 is cut means that the easier our stuff is to actually get it -- and then we can add to it in 26.  Note I did ask the LEWG chair in the last week if he thought it was worth it for us to pursue this for 23 given all the work and he said yes.

**Comment by JeffGarland** [comment]
I've done the 10 minute scan of the changes -- will look more latter, but the general direction looks good.  Looks like you already pulled the pipes...

**Pull request closed without merging**
